### ISSUE TITLE
[bug] not back to correct line whe exit from tui tool

### ISSUE THREAD

**Issue by DreamMaoMao** [veltza/st-sx#15]
st-sx:

https://github.com/user-attachments/assets/cee81a9c-a9f2-4d43-983c-7de9fd21018e

foot:

https://github.com/user-attachments/assets/49d45510-a2fc-4129-980e-41c77fe8e151

foot can return to the right line to conitnue , st-sx make a mistake here,  it return to first line.
the test tui tool  is yazi.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/user-attachments/assets/79df44ef-55a1-4bcb-a6a4-f40d78c89dab)
there is a error here.

**Comment by veltza** [comment]
I can't reproduce this issue with Yazi version 0.4.2, so I need more information to reproduce it.

1. What Yazi version are you using?
2. What kind of shell are you using? Bash, Zsh or something else?
3. Does this also happen on the vanilla st as well? 
4. Are you using a [wrapper script](https://yazi-rs.github.io/docs/quick-start#shell-wrapper) to start Yazi?
5. Is there anything else to consider? Yazi plugins?

---

Yazi causes the following error messages on startup in st-sx and they should not affect Yazi's functionality:

* ```erresc: unknown csi esc[?12$p```

Yazi queries the terminal for the cursor blink status as you can see [here](https://github.com/sxyazi/yazi/blob/d754ac5dac10e7ad38243552711828ab1e9f25f4/yazi-fm/src/term.rs#L36). Since st and st-sx do not have or use the cursor blink status, they will not respond to this request, and Yazi should work fine without this information.

* ```erresc: unknown csi esc[>q```

Here, Yazi tries to identify the terminal and [queries](https://github.com/sxyazi/yazi/blob/d754ac5dac10e7ad38243552711828ab1e9f25f4/yazi-adapter/src/emulator.rs#L42) its version. Since Yazi doesn't know the st terminal, and st and st-sx don't support this query, it doesn't matter if Yazi doesn't get an answer to it.

**Comment by veltza** [comment]
One more question. What kind of shell prompt are you using? Have you tried a very basic prompt?

**Comment by DreamMaoMao** [comment]
I still have this problem when I try to use bash in its original form. yazi version is this latest version.
i also try use original config yazi.

I have a more stable method of reproduction

1. open yazi 
2. use this way to open shell
![image](https://github.com/user-attachments/assets/c0dbec11-3f8d-4cd1-9393-303638df8808)

3. keydown few return key to do something

4. input exit to return to yazi

5. use the setep2 to open shell agiain

**Comment by veltza** [comment]
I found the bug and it is inherited from the vanilla st, so it's there too. I will fix it as soon as possible.

**Comment by veltza** [comment]
I wrote a [patch](https://github.com/veltza/st-sx/commit/52cf6f0c912ba9f70e414864f23617313fb6e75a) that should fix this issue. Could you please confirm that it works in your case as well?

**Comment by DreamMaoMao** [comment]
nice , it was fixed.
